### PR TITLE
Feature/create forms

### PR DESCRIPTION
**Pull request by Felipe-Perez-Ferraro**
- Added new routes
- Created the current_user instance
- Created comments_controller
- Created likes_controller
- Added new and create methods to posts_controller
- Created new.html.erb file to views/comments
- Created new.html.erb file to views/posts
- Added a background color to the body
- Updated index.html.erb file in views/posts
- Added the like and comment buttons
- Fixed linter errors

### CODE REVIEW

**Comment by rloterh** [comment]
Hi @Felipe-Perez-Ferraro 
**Stylelint** linter check is missing! Kindly ensure to add it asap!

Cheers!

**Comment by rloterh** [comment]
@Felipe-Perez-Ferraro 
Nice job! Almost there!

Let's also remove the underlined from the ReadMe:

image

Cheers!

**Comment by Felipe-Perez-Ferraro** [comment]
hi okay, i will change it, thank you

**Review by rloterh — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi Feli,  

**Blog app - add forms** task is complete! 🏁 Congratulations!  🎉💯🌟 

## Highlights 🎯 
🎲 New post can be successfully added by a user!
🎲 Comments and likes can be made on a post!
🎲 ReadMe looks good!

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
